#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop
# for the 9th iteration displays "Best School" and then hi

counter=0
while [ $counter -lt 10 ]
do
  echo "Best School"
  if [ $counter -eq 9 ]
  then
    echo "Hi"
  fi
  ((counter++))
done
