#!/usr/bin/env bash
# gives you information about the school file

if test -a "school";then
    echo "school file exists"
      if [ -s school ];then
        echo "school file is not empty"
      else
        echo "school file is empty"
      fi
      if test -f "school";then
        echo "school is a regular file"
      fi
elif test -d "school";then
    echo "school file exists"
      if [ "$(ls -A school)" ];then
        echo "school is not empty"
      else
        echo "school is empty"
      fi
else
    echo "school file does not exist"
fi
