#!/usr/bin/env bash
# This script displays "bad luck" for the 4th position, "good luck" for the 8th position
# and displays "Best School" for other iterations

counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 4 ]
  then
    echo "good luck"
  elif [ $counter -eq 8 ]
  then
    echo "bad luck"
  else
    echo "Best School"
  fi
  ((counter++))
done